version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'djangodb'
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_pass
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $$(cat $${POSTGRES_USER_FILE})" ]
      interval: 30s
      timeout: 5s
      retries: 5
    secrets:
      - postgres_user
      - postgres_pass

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=resume_website.settings
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    user: django
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8000/" ]
      interval: 30s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/src/app/static:ro
      - media_volume:/usr/src/app/media:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    user: cloudflared

secrets:
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_pass:
    file: ./secrets/postgres_password.txt

volumes:
  static_volume:
  media_volume: