version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'djangodb'
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $$(cat $${POSTGRES_USER_FILE})" ]
      interval: 30s
      timeout: 5s
      retries: 5

  web:
    image: ghcr.io/adithya-rajendran/personal_website:latest
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=resume_website.settings
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    user: django
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8000/" ]
      interval: 30s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/usr/src/app/static:ro
      - media_volume:/usr/src/app/media:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - db
      - web

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    user: cloudflared

volumes:
  static_volume:
  media_volume: