version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=resume_website.settings
    secrets:
      - email_secrets

secrets:
  email_secrets:
    file: secrets/email_secrets.txt